apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-config.yaml
  - ./check-modules-config.yaml
  - ./status-config.yaml
  - ./rbac.yaml
  - ./deployment.yaml
  - ./service.yaml
