apiVersion: v1
kind: Service
metadata:
  name: kubecrate-status
  labels:
    app.kubernetes.io/name: kubecrate-status
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: application-services
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubecrate-status
  ports:
    - name: http
      port: 80
      targetPort: http
