apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: core-cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  interval: 30m0s
  url: https://charts.jetstack.io
