apiVersion: v1
kind: Namespace
metadata:
  name: core-cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
