apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: core-external-secrets-operator
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  interval: 30m0s
  url: https://charts.external-secrets.io
