apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./helm-repository.yaml
  - ./helm-release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: external-secrets-operator-values
    namespace: core-external-secrets-operator
    files:
      - values.yaml=./helm-values.yaml
