apiVersion: v1
kind: Namespace
metadata:
  name: core-external-secrets-operator
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
