fullnameOverride: external-secrets
installCRDs: true
concurrent: 1
log:
  level: info
  timeEncoding: epoch
serviceAccount:
  name: external-secrets
rbac:
  servicebindings:
    create: false
  aggregateToView: false
  aggregateToEdit: false
webhook:
  create: false
certController:
  create: false
