apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: core-external-secrets-operator
spec:
  selector:
    matchLabels:
      $patch: replace
      app.kubernetes.io/name: external-secrets
  template:
    spec:
      containers:
        - name: external-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
