apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  interval: 1m0s
  path: ./clusters/kind-dev-misc-local/platform-services/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system-sync
  timeout: 5m0s
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: core-cert-manager
