apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-sync-values-override
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux-system-sync
    app.kubernetes.io/part-of: kubecrate
data:
  values.yaml: |
    {}
