apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecrate-reconciliation-marker
  namespace: kubecrate-system
  labels:
    app.kubernetes.io/name: kubecrate-reconciliation-marker
    app.kubernetes.io/part-of: kubecrate
data:
  version: v0.1.0
