apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kubecrate-system-namespace.yaml
  - ../platform-services/flux
  - ../application-services/kubecrate-status
  - ./kubecrate-reconciliation-marker.yaml
