secret:
  create: true
gitRepository:
  spec:
    url: ssh://git@github.com/42aei/kubecrate.git
    interval: 1m
    ref:
      branch: hermes/validation-status-flux-inspection
kustomization:
  spec:
    interval: 1m
    path: ./clusters/kind-dev-misc-local/entrypoint
    prune: true
    timeout: 5m
    wait: false
