secret:
  create: true
  generate:
    sshKeyAlgorithm: ed25519
gitRepository:
  spec:
    url: ssh://git@github.com/42aei/kubecrate.git
    interval: 1m
    ref:
      branch: main
kustomization:
  spec:
    interval: 1m
    path: ./clusters/kind-dev-misc-local/entrypoint
    prune: true
    timeout: 5m
    wait: false
